In [33]:
import pandas as pd
import numpy as np

In [92]:
grpo_best_path = "../result/grpo/grpo_return_33.csv"
grpo_worst_path = "../result/grpo/grpo_return_42.csv"
ppo_best_path = "../result/ppo/ppo_return_25.csv"
ppo_worst_path = "../result/ppo/ppo_return_50.csv"
sac_best_path = "../result/sac/sac_return_50.csv"
sac_worst_path = "../result/sac/sac_return_39.csv"
equal_strategy_path = "../result/equal_strategy.csv"

In [93]:
grpo_best = pd.read_csv(sac_worst_path, index_col=0)

In [94]:
grpo_best

               Model
2019-01-30 -0.023335
2019-02-28 -0.016946
2019-03-28 -0.012795
2019-04-26  0.021245
2019-05-24 -0.034561
...              ...
2024-09-20  0.001493
2024-10-18  0.016962
2024-11-15 -0.020194
2024-12-16  0.078830
2024-12-31 -0.000110

[76 rows x 1 columns]

In [95]:
# grpo_best = grpo_best[["equal_asset_weight"]]
# grpo_best.rename(columns={"equal_asset_weight": "Model"}, inplace=True)

In [96]:
gross_profit = grpo_best[grpo_best["Model"] >= 0].sum()

In [97]:
gross_profit

Model    1.722928
dtype: float64

In [98]:
gross_loss = abs(grpo_best[grpo_best["Model"] < 0].sum())

In [99]:
grpo_best[grpo_best["Model"] >= 0].describe()

           Model
count  38.000000
mean    0.045340
std     0.038650
min     0.001057
25%     0.017066
50%     0.036555
75%     0.076441
max     0.178793

In [100]:
grpo_best[grpo_best["Model"] < 0].describe()

           Model
count  38.000000
mean   -0.039892
std     0.043159
min    -0.156020
25%    -0.051317
50%    -0.022755
75%    -0.010538
max    -0.000110

In [101]:
(grpo_best<0).sum()

Model    38
dtype: int64

In [102]:
gross_loss

Model    1.515882
dtype: float64

In [89]:
profit_factor = gross_profit.values / gross_loss.values if gross_loss.values != 0 else np.inf

In [90]:
profit_factor

array([1.13658456])

In [91]:
print("profitable_month" , (grpo_best>=0).sum()
        , "unprofitable_month" , (grpo_best<0).sum())

profitable_month Model    38
dtype: int64 unprofitable_month Model    38
dtype: int64

In [111]:
# 1. 인덱스를 datetime 형식으로 변환
grpo_best.index = pd.to_datetime(grpo_best.index)

In [112]:
grpo_best['year'] = grpo_best.index.year

In [114]:

# 3. 연도별 수익률 합계
yearly_return = grpo_best.groupby('year')['Model'].sum()

In [115]:
# 4. 수익이 난 해 / 손실이 난 해 개수
profitable_years = (yearly_return > 0).sum()
unprofitable_years = (yearly_return <= 0).sum()

print(f"Profitable years: {profitable_years}, Unprofitable years: {unprofitable_years}")

Profitable years: 5, Unprofitable years: 1